// <auto-generated />
using System;
using FPIS.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPIS.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220131003025_data3")]
    partial class data3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Broj", b =>
                {
                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<int>("IDUlice")
                        .HasColumnType("int");

                    b.Property<int>("BrojAdrese")
                        .HasColumnType("int");

                    b.HasKey("PostanskiBroj", "IDUlice", "BrojAdrese");

                    b.HasIndex("IDUlice", "PostanskiBroj");

                    b.ToTable("Broj");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Delatnost", b =>
                {
                    b.Property<int>("SifraDel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SifraDel"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifraDel");

                    b.ToTable("Delatnost");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", b =>
                {
                    b.Property<int>("IDKlijenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKlijenta"), 1L, 1);

                    b.Property<int>("BrojAdrese")
                        .HasColumnType("int");

                    b.Property<int>("GodinaOsnivanja")
                        .HasColumnType("int");

                    b.Property<int>("IDPotKlijenta")
                        .HasColumnType("int");

                    b.Property<int>("IDUlice")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<int>("SifraDel")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebStrana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKlijenta");

                    b.HasIndex("IDPotKlijenta");

                    b.HasIndex("SifraDel");

                    b.HasIndex("PostanskiBroj", "IDUlice", "BrojAdrese");

                    b.ToTable("Klijent");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Mesto", b =>
                {
                    b.Property<int>("PostanskiBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostanskiBroj"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostanskiBroj");

                    b.ToTable("Mesto");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Operater", b =>
                {
                    b.Property<int>("IDOperatera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOperatera"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDOperatera");

                    b.ToTable("Operater");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.OrganizacionaJedinica", b =>
                {
                    b.Property<int>("IDOrgJed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOrgJed"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDOrgJed");

                    b.ToTable("OrganizacionaJedinica");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.PotencijalniKlijent", b =>
                {
                    b.Property<int>("IDPotKlijenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPotKlijenta"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZaposleniPrimaId")
                        .HasColumnType("int");

                    b.Property<int>("ZaposleniSaljeId")
                        .HasColumnType("int");

                    b.HasKey("IDPotKlijenta");

                    b.HasIndex("ZaposleniPrimaId");

                    b.HasIndex("ZaposleniSaljeId");

                    b.ToTable("PotencijalniKlijent");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Pozicija", b =>
                {
                    b.Property<int>("IDPoz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPoz"), 1L, 1);

                    b.Property<int>("IDOrgJed")
                        .HasColumnType("int");

                    b.Property<int?>("IDPoz1")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPoz");

                    b.HasIndex("IDOrgJed");

                    b.HasIndex("IDPoz1");

                    b.ToTable("Pozicija");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Ulica", b =>
                {
                    b.Property<int>("IDUlice")
                        .HasColumnType("int");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUlice", "PostanskiBroj");

                    b.HasIndex("PostanskiBroj");

                    b.ToTable("Ulica");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.ZahtevZaPodacima", b =>
                {
                    b.Property<int>("IDZahteva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZahteva"), 1L, 1);

                    b.Property<string>("BrSIMKartica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrZaposlenih")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IDKlijenta")
                        .HasColumnType("int");

                    b.Property<int>("IDOperatera")
                        .HasColumnType("int");

                    b.Property<int>("IDZap")
                        .HasColumnType("int");

                    b.HasKey("IDZahteva");

                    b.HasIndex("IDKlijenta");

                    b.HasIndex("IDOperatera");

                    b.HasIndex("IDZap")
                        .IsUnique();

                    b.ToTable("ZahtevZaPodacima");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", b =>
                {
                    b.Property<int>("IDZap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZap"), 1L, 1);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDZPoz")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDZap");

                    b.HasIndex("IDZPoz");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Kredit", b =>
                {
                    b.Property<int>("IDKr")
                        .HasColumnType("int");

                    b.Property<int>("SifraVrsteKr")
                        .HasColumnType("int");

                    b.Property<int>("IDKlijenta")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumKrajaOtplate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPocetkaKoriscenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPocetkaOtplate")
                        .HasColumnType("datetime2");

                    b.Property<double>("IskorisceniIznos")
                        .HasColumnType("float");

                    b.Property<double>("OdobreniIznos")
                        .HasColumnType("float");

                    b.Property<double>("OstatakDuga")
                        .HasColumnType("float");

                    b.Property<int>("PeriodOtplate")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKr", "SifraVrsteKr", "IDKlijenta");

                    b.HasIndex("IDKlijenta");

                    b.HasIndex("SifraVrsteKr");

                    b.ToTable("Kredit");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.PonudaUredjajaITarifnihPaketa", b =>
                {
                    b.Property<int>("IDPounde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPounde"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDKlijenta")
                        .HasColumnType("int");

                    b.Property<int>("IDZap")
                        .HasColumnType("int");

                    b.HasKey("IDPounde");

                    b.HasIndex("IDKlijenta");

                    b.HasIndex("IDZap");

                    b.ToTable("PonudaUredjajaITarifnihPaketa");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Proizvodjac", b =>
                {
                    b.Property<int>("IDProizvodjaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProizvodjaca"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProizvodjaca");

                    b.ToTable("Proizvodjac");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.StavkaPonude", b =>
                {
                    b.Property<int>("Rbr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rbr"), 1L, 1);

                    b.Property<int>("IDPonude")
                        .HasColumnType("int");

                    b.Property<int>("IDTF")
                        .HasColumnType("int");

                    b.Property<int>("IDUredjaja")
                        .HasColumnType("int");

                    b.Property<int>("UredjajIDUredjaja")
                        .HasColumnType("int");

                    b.HasKey("Rbr");

                    b.HasIndex("IDPonude");

                    b.HasIndex("IDTF");

                    b.HasIndex("UredjajIDUredjaja");

                    b.ToTable("StavkaPonude");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TarifniPaket", b =>
                {
                    b.Property<int>("IDTF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTF"), 1L, 1);

                    b.Property<int>("BrojMB")
                        .HasColumnType("int");

                    b.Property<int>("BrojMinuta")
                        .HasColumnType("int");

                    b.Property<int>("BrojPoruka")
                        .HasColumnType("int");

                    b.Property<int>("IDVrste")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VrstaPaketaIDVrste")
                        .HasColumnType("int");

                    b.HasKey("IDTF");

                    b.HasIndex("VrstaPaketaIDVrste");

                    b.ToTable("TarifniPaket");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TekuciRacun", b =>
                {
                    b.Property<int>("IDTR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTR"), 1L, 1);

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivNosiocaRacuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProsecanMesecniOdliv")
                        .HasColumnType("float");

                    b.Property<double>("ProsecanMesecniPriliv")
                        .HasColumnType("float");

                    b.Property<int>("SifraValute")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTR");

                    b.HasIndex("SifraValute");

                    b.ToTable("TekuciRacun");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Uredjaj", b =>
                {
                    b.Property<int>("IDUredjaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUredjaja"), 1L, 1);

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("IDProizvodjaca")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUredjaja");

                    b.HasIndex("IDProizvodjaca");

                    b.ToTable("Uredjaj");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Valuta", b =>
                {
                    b.Property<int>("SifraValute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SifraValute"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifraValute");

                    b.ToTable("Valuta");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaKredita", b =>
                {
                    b.Property<int>("SifraVrsteKr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SifraVrsteKr"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SifraValute")
                        .HasColumnType("int");

                    b.HasKey("SifraVrsteKr");

                    b.HasIndex("SifraValute");

                    b.ToTable("VrstaKredita");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaPaketa", b =>
                {
                    b.Property<int>("IDVrste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVrste"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDVrste");

                    b.ToTable("VrstaPaketa");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.ZahtevZaProveruKreditneSposobnosti", b =>
                {
                    b.Property<int>("IDZahteva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZahteva"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDKlijenta")
                        .HasColumnType("int");

                    b.Property<int>("IDKr")
                        .HasColumnType("int");

                    b.Property<int>("IDTR")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniPrima")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniSalje")
                        .HasColumnType("int");

                    b.Property<string>("NacinDostave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SifraVrsteKr")
                        .HasColumnType("int");

                    b.HasKey("IDZahteva");

                    b.HasIndex("IDKlijenta");

                    b.HasIndex("IDTR");

                    b.HasIndex("IDZaposleniPrima");

                    b.HasIndex("IDZaposleniSalje");

                    b.HasIndex("SifraVrsteKr");

                    b.HasIndex("IDKr", "SifraVrsteKr", "IDKlijenta");

                    b.ToTable("ZahtevZaProveruKreditneSposobnosti");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Ponuda", b =>
                {
                    b.Property<int>("IDPonude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPonude"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDProracuna")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokPrihvatanja")
                        .HasColumnType("datetime2");

                    b.HasKey("IDPonude");

                    b.HasIndex("IDProracuna");

                    b.ToTable("Ponuda");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Proracun", b =>
                {
                    b.Property<int>("IDProracuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProracuna"), 1L, 1);

                    b.Property<double>("CenaSaPopustom")
                        .HasColumnType("float");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPonude")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniPrima")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniSalje")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PonudaUredjajaITarifnihPaketaIDPounde")
                        .HasColumnType("int");

                    b.Property<double>("Popust")
                        .HasColumnType("float");

                    b.HasKey("IDProracuna");

                    b.HasIndex("IDZaposleniPrima");

                    b.HasIndex("IDZaposleniSalje");

                    b.HasIndex("PonudaUredjajaITarifnihPaketaIDPounde");

                    b.ToTable("Proracun");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaPonudeSklapanjeUgovora", b =>
                {
                    b.Property<int>("Rbr")
                        .HasColumnType("int");

                    b.Property<int>("IDPonude")
                        .HasColumnType("int");

                    b.Property<int>("IDProracuna")
                        .HasColumnType("int");

                    b.Property<int>("RbrStavkaProracuna")
                        .HasColumnType("int");

                    b.HasKey("Rbr", "IDPonude");

                    b.HasIndex("IDPonude");

                    b.HasIndex("IDProracuna");

                    b.HasIndex("Rbr", "IDProracuna");

                    b.ToTable("StavkaPonudeSklapanjeUgovora");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaProracuna", b =>
                {
                    b.Property<int>("Rbr")
                        .HasColumnType("int");

                    b.Property<int>("IDProracuna")
                        .HasColumnType("int");

                    b.Property<int>("IDTF")
                        .HasColumnType("int");

                    b.Property<int>("IDUredjaja")
                        .HasColumnType("int");

                    b.HasKey("Rbr", "IDProracuna");

                    b.HasIndex("IDProracuna");

                    b.HasIndex("IDTF");

                    b.HasIndex("IDUredjaja");

                    b.ToTable("StavkaProracuna");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaZahteva", b =>
                {
                    b.Property<int>("Rbr")
                        .HasColumnType("int");

                    b.Property<int>("IDZahteva")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rbr", "IDZahteva");

                    b.HasIndex("IDZahteva");

                    b.ToTable("StavkaZahteva");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Ugovor", b =>
                {
                    b.Property<int>("IDUgovora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUgovora"), 1L, 1);

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDPonude")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniPotpisuje")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniProverava")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUgovora");

                    b.HasIndex("IDPonude");

                    b.HasIndex("IDZaposleniPotpisuje");

                    b.HasIndex("IDZaposleniProverava");

                    b.ToTable("Ugovor");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.ZahtevZaProveruTehnickihUsluga", b =>
                {
                    b.Property<int>("IDZahteva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDZahteva"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDZaposleniPrima")
                        .HasColumnType("int");

                    b.Property<int>("IDZaposleniSalje")
                        .HasColumnType("int");

                    b.Property<bool>("Odobreno")
                        .HasColumnType("bit");

                    b.HasKey("IDZahteva");

                    b.HasIndex("IDZaposleniPrima");

                    b.HasIndex("IDZaposleniSalje");

                    b.ToTable("ZahtevZaProveruTehnickihUsluga");
                });

            modelBuilder.Entity("FPIS.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FPIS.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CellphoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a11d81dd-6f14-4dbd-9b8b-a4ba91c56899",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Petar",
                            PasswordHash = "AQAAAAEAACcQAAAAEF86Dfi2WPUtkA0Cdeil/upywlra5weoG4xlLV+0UbtwxxSksBrWk8fG00wXUp/gbw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            Surname = "Todic",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("FPIS.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("FPIS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LoginToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Broj", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Mesto", "Mesto")
                        .WithMany("Brojevi")
                        .HasForeignKey("PostanskiBroj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Ulica", "Ulica")
                        .WithMany("Brojevi")
                        .HasForeignKey("IDUlice", "PostanskiBroj")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mesto");

                    b.Navigation("Ulica");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.PotencijalniKlijent", "PotencijalniKlijent")
                        .WithMany()
                        .HasForeignKey("IDPotKlijenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Mesto", "Mesto")
                        .WithMany()
                        .HasForeignKey("PostanskiBroj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Delatnost", "Delatnost")
                        .WithMany("Klijenti")
                        .HasForeignKey("SifraDel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Ulica", "Ulica")
                        .WithMany("Klijenti")
                        .HasForeignKey("PostanskiBroj", "IDUlice")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Broj", "Broj")
                        .WithMany("Klijenti")
                        .HasForeignKey("PostanskiBroj", "IDUlice", "BrojAdrese")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Broj");

                    b.Navigation("Delatnost");

                    b.Navigation("Mesto");

                    b.Navigation("PotencijalniKlijent");

                    b.Navigation("Ulica");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.PotencijalniKlijent", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniPrima")
                        .WithMany("PotencijalniKlijentPrima")
                        .HasForeignKey("ZaposleniPrimaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniSalje")
                        .WithMany("PotencijalniKlijentSalje")
                        .HasForeignKey("ZaposleniSaljeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ZaposleniPrima");

                    b.Navigation("ZaposleniSalje");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Pozicija", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.OrganizacionaJedinica", "OrganizacionaJedinica")
                        .WithMany("Pozicije")
                        .HasForeignKey("IDOrgJed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Pozicija", "Pozicija1")
                        .WithMany("Pozicije")
                        .HasForeignKey("IDPoz1");

                    b.Navigation("OrganizacionaJedinica");

                    b.Navigation("Pozicija1");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Ulica", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Mesto", "Mesto")
                        .WithMany("Ulice")
                        .HasForeignKey("PostanskiBroj")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mesto");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.ZahtevZaPodacima", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", "Klijent")
                        .WithMany("ZahteviZaPodacima")
                        .HasForeignKey("IDKlijenta");

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Operater", "Operater")
                        .WithMany()
                        .HasForeignKey("IDOperatera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "Zaposleni")
                        .WithOne("zahtevZaPodacima")
                        .HasForeignKey("FPIS.Entities._1_Identifikacija_novih_klijenata.ZahtevZaPodacima", "IDZap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Operater");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Pozicija", "Pozicija")
                        .WithMany("Zaposleni")
                        .HasForeignKey("IDZPoz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozicija");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Kredit", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", "Klijent")
                        .WithMany("Krediti")
                        .HasForeignKey("IDKlijenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaKredita", "VrstaKredita")
                        .WithMany("Krediti")
                        .HasForeignKey("SifraVrsteKr")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("VrstaKredita");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.PonudaUredjajaITarifnihPaketa", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", "Klijent")
                        .WithMany("PonudeUredjajaITarifnihPaketa")
                        .HasForeignKey("IDKlijenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "Zaposleni")
                        .WithMany()
                        .HasForeignKey("IDZap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.StavkaPonude", b =>
                {
                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.PonudaUredjajaITarifnihPaketa", "PonudaUredjajaITarifnihPaketa")
                        .WithMany("StavkePonude")
                        .HasForeignKey("IDPonude")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TarifniPaket", "TarifniPaket")
                        .WithMany("StavkePonude")
                        .HasForeignKey("IDTF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Uredjaj", "Uredjaj")
                        .WithMany("StavkePonude")
                        .HasForeignKey("UredjajIDUredjaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PonudaUredjajaITarifnihPaketa");

                    b.Navigation("TarifniPaket");

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TarifniPaket", b =>
                {
                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaPaketa", "VrstaPaketa")
                        .WithMany("TarifniPaketi")
                        .HasForeignKey("VrstaPaketaIDVrste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VrstaPaketa");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TekuciRacun", b =>
                {
                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Valuta", "Valuta")
                        .WithMany("TekuciRacuni")
                        .HasForeignKey("SifraValute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Valuta");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Uredjaj", b =>
                {
                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Proizvodjac", "Proizvodjac")
                        .WithMany("Uredjaji")
                        .HasForeignKey("IDProizvodjaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvodjac");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaKredita", b =>
                {
                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Valuta", "Valuta")
                        .WithMany("VrsteKredita")
                        .HasForeignKey("SifraValute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Valuta");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.ZahtevZaProveruKreditneSposobnosti", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", "Klijent")
                        .WithMany()
                        .HasForeignKey("IDKlijenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TekuciRacun", "TekuciRacun")
                        .WithMany("ZahteviZaProveruKreditneSposobnosti")
                        .HasForeignKey("IDTR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniPrima")
                        .WithMany("ZahteviZaProveruKreditneSposobnostiPrima")
                        .HasForeignKey("IDZaposleniPrima")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniSalje")
                        .WithMany("ZahteviZaProveruKreditneSposobnostiSalje")
                        .HasForeignKey("IDZaposleniSalje")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaKredita", "VrstaKredita")
                        .WithMany("ZahteviZaProveruKreditneSposobnosti")
                        .HasForeignKey("SifraVrsteKr")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Kredit", "Kredit")
                        .WithMany("ZahteviZaProveruKreditneSposobnosti")
                        .HasForeignKey("IDKr", "SifraVrsteKr", "IDKlijenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Kredit");

                    b.Navigation("TekuciRacun");

                    b.Navigation("VrstaKredita");

                    b.Navigation("ZaposleniPrima");

                    b.Navigation("ZaposleniSalje");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Ponuda", b =>
                {
                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.Proracun", "Proracun")
                        .WithMany()
                        .HasForeignKey("IDProracuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proracun");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Proracun", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniPrima")
                        .WithMany("ProracunPrima")
                        .HasForeignKey("IDZaposleniPrima")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniSalje")
                        .WithMany("ProracunSalje")
                        .HasForeignKey("IDZaposleniSalje")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.PonudaUredjajaITarifnihPaketa", "PonudaUredjajaITarifnihPaketa")
                        .WithMany()
                        .HasForeignKey("PonudaUredjajaITarifnihPaketaIDPounde")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PonudaUredjajaITarifnihPaketa");

                    b.Navigation("ZaposleniPrima");

                    b.Navigation("ZaposleniSalje");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaPonudeSklapanjeUgovora", b =>
                {
                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("IDPonude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.Proracun", "Proracun")
                        .WithMany("StavkePonudeSklapanjeUgovora")
                        .HasForeignKey("IDProracuna")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.StavkaProracuna", "StavkaProracuna")
                        .WithMany("StavkePonudeSklapanjeUgovora")
                        .HasForeignKey("Rbr", "IDProracuna")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("Proracun");

                    b.Navigation("StavkaProracuna");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaProracuna", b =>
                {
                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.Proracun", "Proracun")
                        .WithMany()
                        .HasForeignKey("IDProracuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TarifniPaket", "TarifniPaket")
                        .WithMany()
                        .HasForeignKey("IDTF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Uredjaj", "Uredjaj")
                        .WithMany()
                        .HasForeignKey("IDUredjaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proracun");

                    b.Navigation("TarifniPaket");

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaZahteva", b =>
                {
                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.ZahtevZaProveruTehnickihUsluga", "ZahtevZaProveruTehnickihUsluga")
                        .WithMany("StavkeZahteva")
                        .HasForeignKey("IDZahteva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZahtevZaProveruTehnickihUsluga");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Ugovor", b =>
                {
                    b.HasOne("FPIS.Entities._3_Sklapanje_ugovora.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("IDPonude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniPotpisuje")
                        .WithMany("UgovorPotpisuje")
                        .HasForeignKey("IDZaposleniPotpisuje")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniProverava")
                        .WithMany("UgovorProverava")
                        .HasForeignKey("IDZaposleniProverava")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("ZaposleniPotpisuje");

                    b.Navigation("ZaposleniProverava");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.ZahtevZaProveruTehnickihUsluga", b =>
                {
                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniPrima")
                        .WithMany("ZahtevZaProveruTehnickihUslugaPrima")
                        .HasForeignKey("IDZaposleniPrima")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", "ZaposleniSalje")
                        .WithMany("ZahtevZaProveruTehnickihUslugaSalje")
                        .HasForeignKey("IDZaposleniSalje")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ZaposleniPrima");

                    b.Navigation("ZaposleniSalje");
                });

            modelBuilder.Entity("FPIS.Entities.AppUserRole", b =>
                {
                    b.HasOne("FPIS.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("FPIS.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FPIS.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FPIS.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FPIS.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Broj", b =>
                {
                    b.Navigation("Klijenti");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Delatnost", b =>
                {
                    b.Navigation("Klijenti");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Klijent", b =>
                {
                    b.Navigation("Krediti");

                    b.Navigation("PonudeUredjajaITarifnihPaketa");

                    b.Navigation("ZahteviZaPodacima");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Mesto", b =>
                {
                    b.Navigation("Brojevi");

                    b.Navigation("Ulice");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.OrganizacionaJedinica", b =>
                {
                    b.Navigation("Pozicije");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Pozicija", b =>
                {
                    b.Navigation("Pozicije");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Ulica", b =>
                {
                    b.Navigation("Brojevi");

                    b.Navigation("Klijenti");
                });

            modelBuilder.Entity("FPIS.Entities._1_Identifikacija_novih_klijenata.Zaposleni", b =>
                {
                    b.Navigation("PotencijalniKlijentPrima");

                    b.Navigation("PotencijalniKlijentSalje");

                    b.Navigation("ProracunPrima");

                    b.Navigation("ProracunSalje");

                    b.Navigation("UgovorPotpisuje");

                    b.Navigation("UgovorProverava");

                    b.Navigation("ZahtevZaProveruTehnickihUslugaPrima");

                    b.Navigation("ZahtevZaProveruTehnickihUslugaSalje");

                    b.Navigation("ZahteviZaProveruKreditneSposobnostiPrima");

                    b.Navigation("ZahteviZaProveruKreditneSposobnostiSalje");

                    b.Navigation("zahtevZaPodacima")
                        .IsRequired();
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Kredit", b =>
                {
                    b.Navigation("ZahteviZaProveruKreditneSposobnosti");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.PonudaUredjajaITarifnihPaketa", b =>
                {
                    b.Navigation("StavkePonude");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Proizvodjac", b =>
                {
                    b.Navigation("Uredjaji");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TarifniPaket", b =>
                {
                    b.Navigation("StavkePonude");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.TekuciRacun", b =>
                {
                    b.Navigation("ZahteviZaProveruKreditneSposobnosti");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Uredjaj", b =>
                {
                    b.Navigation("StavkePonude");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.Valuta", b =>
                {
                    b.Navigation("TekuciRacuni");

                    b.Navigation("VrsteKredita");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaKredita", b =>
                {
                    b.Navigation("Krediti");

                    b.Navigation("ZahteviZaProveruKreditneSposobnosti");
                });

            modelBuilder.Entity("FPIS.Entities._2_Prikupljanje_potrebnih_informacija_o_klijentu.VrstaPaketa", b =>
                {
                    b.Navigation("TarifniPaketi");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.Proracun", b =>
                {
                    b.Navigation("StavkePonudeSklapanjeUgovora");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.StavkaProracuna", b =>
                {
                    b.Navigation("StavkePonudeSklapanjeUgovora");
                });

            modelBuilder.Entity("FPIS.Entities._3_Sklapanje_ugovora.ZahtevZaProveruTehnickihUsluga", b =>
                {
                    b.Navigation("StavkeZahteva");
                });

            modelBuilder.Entity("FPIS.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FPIS.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
